/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthApiDocsRouteImport } from './routes/_auth/api-docs'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminOrgsRouteImport } from './routes/_auth/admin/orgs'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthOrgsOrgIdRouteImport } from './routes/_auth/orgs/$orgId'
import { Route as AuthOrgsOrgIdIndexRouteImport } from './routes/_auth/orgs/$orgId/index'
import { Route as AuthOrgsOrgIdActivityRouteImport } from './routes/_auth/orgs/$orgId/activity'
import { Route as AuthOrgsOrgIdMyIssuesRouteImport } from './routes/_auth/orgs/$orgId/my-issues'
import { Route as AuthOrgsOrgIdSettingsRouteRouteImport } from './routes/_auth/orgs/$orgId/settings/route'
import { Route as AuthOrgsOrgIdProjectsIndexRouteImport } from './routes/_auth/orgs/$orgId/projects.index'
import { Route as AuthOrgsOrgIdSettingsIndexRouteImport } from './routes/_auth/orgs/$orgId/settings/index'
import { Route as AuthOrgsOrgIdSettingsApiKeysRouteImport } from './routes/_auth/orgs/$orgId/settings/api-keys'
import { Route as AuthOrgsOrgIdSettingsBillingRouteImport } from './routes/_auth/orgs/$orgId/settings/billing'
import { Route as AuthOrgsOrgIdSettingsLabelsRouteImport } from './routes/_auth/orgs/$orgId/settings/labels'
import { Route as AuthOrgsOrgIdSettingsMembersRouteImport } from './routes/_auth/orgs/$orgId/settings/members'
import { Route as AuthOrgsOrgIdSettingsWebhooksRouteImport } from './routes/_auth/orgs/$orgId/settings/webhooks'
import { Route as AuthOrgsOrgIdProjectsProjectIdIndexRouteImport } from './routes/_auth/orgs/$orgId/projects/$projectId.index'
import { Route as AuthOrgsOrgIdProjectsProjectIdIssueNumberRouteImport } from './routes/_auth/orgs/$orgId/projects/$projectId/$issueNumber'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApiDocsRoute = AuthApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminOrgsRoute = AuthAdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthOrgsOrgIdRoute = AuthOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgsOrgIdIndexRoute = AuthOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)
const AuthOrgsOrgIdActivityRoute = AuthOrgsOrgIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)
const AuthOrgsOrgIdMyIssuesRoute = AuthOrgsOrgIdMyIssuesRouteImport.update({
  id: '/my-issues',
  path: '/my-issues',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)
const AuthOrgsOrgIdSettingsRouteRoute =
  AuthOrgsOrgIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthOrgsOrgIdRoute,
  } as any)
const AuthOrgsOrgIdProjectsIndexRoute =
  AuthOrgsOrgIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthOrgsOrgIdRoute,
  } as any)
const AuthOrgsOrgIdSettingsIndexRoute =
  AuthOrgsOrgIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthOrgsOrgIdSettingsRouteRoute,
  } as any)
const AuthOrgsOrgIdSettingsApiKeysRoute =
  AuthOrgsOrgIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthOrgsOrgIdSettingsRouteRoute,
  } as any)
const AuthOrgsOrgIdSettingsBillingRoute =
  AuthOrgsOrgIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthOrgsOrgIdSettingsRouteRoute,
  } as any)
const AuthOrgsOrgIdSettingsLabelsRoute =
  AuthOrgsOrgIdSettingsLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthOrgsOrgIdSettingsRouteRoute,
  } as any)
const AuthOrgsOrgIdSettingsMembersRoute =
  AuthOrgsOrgIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthOrgsOrgIdSettingsRouteRoute,
  } as any)
const AuthOrgsOrgIdSettingsWebhooksRoute =
  AuthOrgsOrgIdSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthOrgsOrgIdSettingsRouteRoute,
  } as any)
const AuthOrgsOrgIdProjectsProjectIdIndexRoute =
  AuthOrgsOrgIdProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthOrgsOrgIdRoute,
  } as any)
const AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute =
  AuthOrgsOrgIdProjectsProjectIdIssueNumberRouteImport.update({
    id: '/projects/$projectId/$issueNumber',
    path: '/projects/$projectId/$issueNumber',
    getParentRoute: () => AuthOrgsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/api-docs': typeof AuthApiDocsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/admin/orgs': typeof AuthAdminOrgsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdRouteWithChildren
  '/admin/': typeof AuthAdminIndexRoute
  '/orgs/$orgId/settings': typeof AuthOrgsOrgIdSettingsRouteRouteWithChildren
  '/orgs/$orgId/activity': typeof AuthOrgsOrgIdActivityRoute
  '/orgs/$orgId/my-issues': typeof AuthOrgsOrgIdMyIssuesRoute
  '/orgs/$orgId/': typeof AuthOrgsOrgIdIndexRoute
  '/orgs/$orgId/settings/api-keys': typeof AuthOrgsOrgIdSettingsApiKeysRoute
  '/orgs/$orgId/settings/billing': typeof AuthOrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/labels': typeof AuthOrgsOrgIdSettingsLabelsRoute
  '/orgs/$orgId/settings/members': typeof AuthOrgsOrgIdSettingsMembersRoute
  '/orgs/$orgId/settings/webhooks': typeof AuthOrgsOrgIdSettingsWebhooksRoute
  '/orgs/$orgId/projects/': typeof AuthOrgsOrgIdProjectsIndexRoute
  '/orgs/$orgId/settings/': typeof AuthOrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/projects/$projectId/$issueNumber': typeof AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute
  '/orgs/$orgId/projects/$projectId/': typeof AuthOrgsOrgIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api-docs': typeof AuthApiDocsRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/': typeof AuthIndexRoute
  '/admin/orgs': typeof AuthAdminOrgsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin': typeof AuthAdminIndexRoute
  '/orgs/$orgId/activity': typeof AuthOrgsOrgIdActivityRoute
  '/orgs/$orgId/my-issues': typeof AuthOrgsOrgIdMyIssuesRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdIndexRoute
  '/orgs/$orgId/settings/api-keys': typeof AuthOrgsOrgIdSettingsApiKeysRoute
  '/orgs/$orgId/settings/billing': typeof AuthOrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/labels': typeof AuthOrgsOrgIdSettingsLabelsRoute
  '/orgs/$orgId/settings/members': typeof AuthOrgsOrgIdSettingsMembersRoute
  '/orgs/$orgId/settings/webhooks': typeof AuthOrgsOrgIdSettingsWebhooksRoute
  '/orgs/$orgId/projects': typeof AuthOrgsOrgIdProjectsIndexRoute
  '/orgs/$orgId/settings': typeof AuthOrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/projects/$projectId/$issueNumber': typeof AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthOrgsOrgIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/api-docs': typeof AuthApiDocsRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/orgs': typeof AuthAdminOrgsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/orgs/$orgId': typeof AuthOrgsOrgIdRouteWithChildren
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/orgs/$orgId/settings': typeof AuthOrgsOrgIdSettingsRouteRouteWithChildren
  '/_auth/orgs/$orgId/activity': typeof AuthOrgsOrgIdActivityRoute
  '/_auth/orgs/$orgId/my-issues': typeof AuthOrgsOrgIdMyIssuesRoute
  '/_auth/orgs/$orgId/': typeof AuthOrgsOrgIdIndexRoute
  '/_auth/orgs/$orgId/settings/api-keys': typeof AuthOrgsOrgIdSettingsApiKeysRoute
  '/_auth/orgs/$orgId/settings/billing': typeof AuthOrgsOrgIdSettingsBillingRoute
  '/_auth/orgs/$orgId/settings/labels': typeof AuthOrgsOrgIdSettingsLabelsRoute
  '/_auth/orgs/$orgId/settings/members': typeof AuthOrgsOrgIdSettingsMembersRoute
  '/_auth/orgs/$orgId/settings/webhooks': typeof AuthOrgsOrgIdSettingsWebhooksRoute
  '/_auth/orgs/$orgId/projects/': typeof AuthOrgsOrgIdProjectsIndexRoute
  '/_auth/orgs/$orgId/settings/': typeof AuthOrgsOrgIdSettingsIndexRoute
  '/_auth/orgs/$orgId/projects/$projectId/$issueNumber': typeof AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute
  '/_auth/orgs/$orgId/projects/$projectId/': typeof AuthOrgsOrgIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/login'
    | '/register'
    | '/admin'
    | '/api-docs'
    | '/onboarding'
    | '/admin/orgs'
    | '/admin/users'
    | '/orgs/$orgId'
    | '/admin/'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/activity'
    | '/orgs/$orgId/my-issues'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/settings/api-keys'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/labels'
    | '/orgs/$orgId/settings/members'
    | '/orgs/$orgId/settings/webhooks'
    | '/orgs/$orgId/projects/'
    | '/orgs/$orgId/settings/'
    | '/orgs/$orgId/projects/$projectId/$issueNumber'
    | '/orgs/$orgId/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/login'
    | '/register'
    | '/api-docs'
    | '/onboarding'
    | '/'
    | '/admin/orgs'
    | '/admin/users'
    | '/admin'
    | '/orgs/$orgId/activity'
    | '/orgs/$orgId/my-issues'
    | '/orgs/$orgId'
    | '/orgs/$orgId/settings/api-keys'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/labels'
    | '/orgs/$orgId/settings/members'
    | '/orgs/$orgId/settings/webhooks'
    | '/orgs/$orgId/projects'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/projects/$projectId/$issueNumber'
    | '/orgs/$orgId/projects/$projectId'
  id:
    | '__root__'
    | '/_auth'
    | '/invite'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/api-docs'
    | '/_auth/onboarding'
    | '/_auth/'
    | '/_auth/admin/orgs'
    | '/_auth/admin/users'
    | '/_auth/orgs/$orgId'
    | '/_auth/admin/'
    | '/_auth/orgs/$orgId/settings'
    | '/_auth/orgs/$orgId/activity'
    | '/_auth/orgs/$orgId/my-issues'
    | '/_auth/orgs/$orgId/'
    | '/_auth/orgs/$orgId/settings/api-keys'
    | '/_auth/orgs/$orgId/settings/billing'
    | '/_auth/orgs/$orgId/settings/labels'
    | '/_auth/orgs/$orgId/settings/members'
    | '/_auth/orgs/$orgId/settings/webhooks'
    | '/_auth/orgs/$orgId/projects/'
    | '/_auth/orgs/$orgId/settings/'
    | '/_auth/orgs/$orgId/projects/$projectId/$issueNumber'
    | '/_auth/orgs/$orgId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/api-docs': {
      id: '/_auth/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthApiDocsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/orgs': {
      id: '/_auth/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AuthAdminOrgsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/orgs/$orgId': {
      id: '/_auth/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthOrgsOrgIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orgs/$orgId/': {
      id: '/_auth/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/activity': {
      id: '/_auth/orgs/$orgId/activity'
      path: '/activity'
      fullPath: '/orgs/$orgId/activity'
      preLoaderRoute: typeof AuthOrgsOrgIdActivityRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/my-issues': {
      id: '/_auth/orgs/$orgId/my-issues'
      path: '/my-issues'
      fullPath: '/orgs/$orgId/my-issues'
      preLoaderRoute: typeof AuthOrgsOrgIdMyIssuesRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/settings': {
      id: '/_auth/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsRouteRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/projects/': {
      id: '/_auth/orgs/$orgId/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgId/projects/'
      preLoaderRoute: typeof AuthOrgsOrgIdProjectsIndexRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/settings/': {
      id: '/_auth/orgs/$orgId/settings/'
      path: '/'
      fullPath: '/orgs/$orgId/settings/'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsIndexRouteImport
      parentRoute: typeof AuthOrgsOrgIdSettingsRouteRoute
    }
    '/_auth/orgs/$orgId/settings/api-keys': {
      id: '/_auth/orgs/$orgId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/orgs/$orgId/settings/api-keys'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsApiKeysRouteImport
      parentRoute: typeof AuthOrgsOrgIdSettingsRouteRoute
    }
    '/_auth/orgs/$orgId/settings/billing': {
      id: '/_auth/orgs/$orgId/settings/billing'
      path: '/billing'
      fullPath: '/orgs/$orgId/settings/billing'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsBillingRouteImport
      parentRoute: typeof AuthOrgsOrgIdSettingsRouteRoute
    }
    '/_auth/orgs/$orgId/settings/labels': {
      id: '/_auth/orgs/$orgId/settings/labels'
      path: '/labels'
      fullPath: '/orgs/$orgId/settings/labels'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsLabelsRouteImport
      parentRoute: typeof AuthOrgsOrgIdSettingsRouteRoute
    }
    '/_auth/orgs/$orgId/settings/members': {
      id: '/_auth/orgs/$orgId/settings/members'
      path: '/members'
      fullPath: '/orgs/$orgId/settings/members'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsMembersRouteImport
      parentRoute: typeof AuthOrgsOrgIdSettingsRouteRoute
    }
    '/_auth/orgs/$orgId/settings/webhooks': {
      id: '/_auth/orgs/$orgId/settings/webhooks'
      path: '/webhooks'
      fullPath: '/orgs/$orgId/settings/webhooks'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsWebhooksRouteImport
      parentRoute: typeof AuthOrgsOrgIdSettingsRouteRoute
    }
    '/_auth/orgs/$orgId/projects/$projectId/': {
      id: '/_auth/orgs/$orgId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/orgs/$orgId/projects/$projectId/'
      preLoaderRoute: typeof AuthOrgsOrgIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/projects/$projectId/$issueNumber': {
      id: '/_auth/orgs/$orgId/projects/$projectId/$issueNumber'
      path: '/projects/$projectId/$issueNumber'
      fullPath: '/orgs/$orgId/projects/$projectId/$issueNumber'
      preLoaderRoute: typeof AuthOrgsOrgIdProjectsProjectIdIssueNumberRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminOrgsRoute: typeof AuthAdminOrgsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminOrgsRoute: AuthAdminOrgsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthOrgsOrgIdSettingsRouteRouteChildren {
  AuthOrgsOrgIdSettingsApiKeysRoute: typeof AuthOrgsOrgIdSettingsApiKeysRoute
  AuthOrgsOrgIdSettingsBillingRoute: typeof AuthOrgsOrgIdSettingsBillingRoute
  AuthOrgsOrgIdSettingsLabelsRoute: typeof AuthOrgsOrgIdSettingsLabelsRoute
  AuthOrgsOrgIdSettingsMembersRoute: typeof AuthOrgsOrgIdSettingsMembersRoute
  AuthOrgsOrgIdSettingsWebhooksRoute: typeof AuthOrgsOrgIdSettingsWebhooksRoute
  AuthOrgsOrgIdSettingsIndexRoute: typeof AuthOrgsOrgIdSettingsIndexRoute
}

const AuthOrgsOrgIdSettingsRouteRouteChildren: AuthOrgsOrgIdSettingsRouteRouteChildren =
  {
    AuthOrgsOrgIdSettingsApiKeysRoute: AuthOrgsOrgIdSettingsApiKeysRoute,
    AuthOrgsOrgIdSettingsBillingRoute: AuthOrgsOrgIdSettingsBillingRoute,
    AuthOrgsOrgIdSettingsLabelsRoute: AuthOrgsOrgIdSettingsLabelsRoute,
    AuthOrgsOrgIdSettingsMembersRoute: AuthOrgsOrgIdSettingsMembersRoute,
    AuthOrgsOrgIdSettingsWebhooksRoute: AuthOrgsOrgIdSettingsWebhooksRoute,
    AuthOrgsOrgIdSettingsIndexRoute: AuthOrgsOrgIdSettingsIndexRoute,
  }

const AuthOrgsOrgIdSettingsRouteRouteWithChildren =
  AuthOrgsOrgIdSettingsRouteRoute._addFileChildren(
    AuthOrgsOrgIdSettingsRouteRouteChildren,
  )

interface AuthOrgsOrgIdRouteChildren {
  AuthOrgsOrgIdSettingsRouteRoute: typeof AuthOrgsOrgIdSettingsRouteRouteWithChildren
  AuthOrgsOrgIdActivityRoute: typeof AuthOrgsOrgIdActivityRoute
  AuthOrgsOrgIdMyIssuesRoute: typeof AuthOrgsOrgIdMyIssuesRoute
  AuthOrgsOrgIdIndexRoute: typeof AuthOrgsOrgIdIndexRoute
  AuthOrgsOrgIdProjectsIndexRoute: typeof AuthOrgsOrgIdProjectsIndexRoute
  AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute: typeof AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute
  AuthOrgsOrgIdProjectsProjectIdIndexRoute: typeof AuthOrgsOrgIdProjectsProjectIdIndexRoute
}

const AuthOrgsOrgIdRouteChildren: AuthOrgsOrgIdRouteChildren = {
  AuthOrgsOrgIdSettingsRouteRoute: AuthOrgsOrgIdSettingsRouteRouteWithChildren,
  AuthOrgsOrgIdActivityRoute: AuthOrgsOrgIdActivityRoute,
  AuthOrgsOrgIdMyIssuesRoute: AuthOrgsOrgIdMyIssuesRoute,
  AuthOrgsOrgIdIndexRoute: AuthOrgsOrgIdIndexRoute,
  AuthOrgsOrgIdProjectsIndexRoute: AuthOrgsOrgIdProjectsIndexRoute,
  AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute:
    AuthOrgsOrgIdProjectsProjectIdIssueNumberRoute,
  AuthOrgsOrgIdProjectsProjectIdIndexRoute:
    AuthOrgsOrgIdProjectsProjectIdIndexRoute,
}

const AuthOrgsOrgIdRouteWithChildren = AuthOrgsOrgIdRoute._addFileChildren(
  AuthOrgsOrgIdRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthApiDocsRoute: typeof AuthApiDocsRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthOrgsOrgIdRoute: typeof AuthOrgsOrgIdRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthApiDocsRoute: AuthApiDocsRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthOrgsOrgIdRoute: AuthOrgsOrgIdRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
