export const ApiErrorCode = {
	INVALID_PARAM: "INVALID_PARAM",
	VALIDATION: "VALIDATION",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	CONFLICT: "CONFLICT",
	PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
	ISSUE_NOT_FOUND: "ISSUE_NOT_FOUND",
	LABEL_NOT_FOUND: "LABEL_NOT_FOUND",
	PROJECT_KEY_TAKEN: "PROJECT_KEY_TAKEN",
	LABEL_NAME_TAKEN: "LABEL_NAME_TAKEN",
	LABEL_IN_USE: "LABEL_IN_USE",
	PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
	COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
	ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
	KEY_MISMATCH: "KEY_MISMATCH",
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
	STORAGE_ERROR: "STORAGE_ERROR",
	SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
	RATE_LIMITED: "RATE_LIMITED",
	API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
	WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",
	WEBHOOK_EVENT_INVALID: "WEBHOOK_EVENT_INVALID",
	PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
	ORG_FROZEN: "ORG_FROZEN",
	BILLING_ERROR: "BILLING_ERROR",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export class ApiError extends Error {
	readonly status: number;
	readonly code: ApiErrorCode | string;

	constructor(status: number, code: ApiErrorCode | string, message: string) {
		super(message);
		this.name = "ApiError";
		this.status = status;
		this.code = code;
	}
}
